// Package repository contains persistence interfaces and PostgreSQL adapters.
// SQL implementations will be generated by sqlc after the initial schema is
// validated against a development PostgreSQL instance.
package repository
