// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contents.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPublishEvent = `-- name: CreatePublishEvent :one
INSERT INTO publish_events (entity_type, entity_id, operation, revision)
VALUES ($1, $2, $3, $4)
RETURNING sequence
`

type CreatePublishEventParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   uuid.UUID   `json:"entity_id"`
	Operation  string      `json:"operation"`
	Revision   pgtype.Int4 `json:"revision"`
}

func (q *Queries) CreatePublishEvent(ctx context.Context, arg CreatePublishEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPublishEvent,
		arg.EntityType,
		arg.EntityID,
		arg.Operation,
		arg.Revision,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const linkContentAsset = `-- name: LinkContentAsset :exec
INSERT INTO content_assets (content_id, asset_id, role, position)
VALUES ($1, $2, $3, $4)
ON CONFLICT (content_id, asset_id, role) DO UPDATE SET position = EXCLUDED.position
`

type LinkContentAssetParams struct {
	ContentID uuid.UUID `json:"content_id"`
	AssetID   uuid.UUID `json:"asset_id"`
	Role      string    `json:"role"`
	Position  int32     `json:"position"`
}

func (q *Queries) LinkContentAsset(ctx context.Context, arg LinkContentAssetParams) error {
	_, err := q.db.Exec(ctx, linkContentAsset,
		arg.ContentID,
		arg.AssetID,
		arg.Role,
		arg.Position,
	)
	return err
}

const listContentsByStatus = `-- name: ListContentsByStatus :many
SELECT id, source_item_id, slug, type, title, summary, level, published_at, duration_seconds, body_blocks, transcript_blocks, metadata, rights_status, attribution, status, revision, source_updated_at, created_at, updated_at, released_at FROM contents
WHERE status = $1
ORDER BY updated_at DESC, id
LIMIT $2
`

type ListContentsByStatusParams struct {
	Status ContentStatus `json:"status"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) ListContentsByStatus(ctx context.Context, arg ListContentsByStatusParams) ([]Content, error) {
	rows, err := q.db.Query(ctx, listContentsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Content{}
	for rows.Next() {
		var i Content
		if err := rows.Scan(
			&i.ID,
			&i.SourceItemID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Level,
			&i.PublishedAt,
			&i.DurationSeconds,
			&i.BodyBlocks,
			&i.TranscriptBlocks,
			&i.Metadata,
			&i.RightsStatus,
			&i.Attribution,
			&i.Status,
			&i.Revision,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContentStatus = `-- name: SetContentStatus :one
UPDATE contents
SET status = $2,
    released_at = CASE
        WHEN status <> 'published'::content_status
             AND $2 = 'published'::content_status THEN now()
        ELSE released_at
    END,
    revision = revision + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, source_item_id, slug, type, title, summary, level, published_at, duration_seconds, body_blocks, transcript_blocks, metadata, rights_status, attribution, status, revision, source_updated_at, created_at, updated_at, released_at
`

type SetContentStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status ContentStatus `json:"status"`
}

func (q *Queries) SetContentStatus(ctx context.Context, arg SetContentStatusParams) (Content, error) {
	row := q.db.QueryRow(ctx, setContentStatus, arg.ID, arg.Status)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SourceItemID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Level,
		&i.PublishedAt,
		&i.DurationSeconds,
		&i.BodyBlocks,
		&i.TranscriptBlocks,
		&i.Metadata,
		&i.RightsStatus,
		&i.Attribution,
		&i.Status,
		&i.Revision,
		&i.SourceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const upsertAsset = `-- name: UpsertAsset :one
INSERT INTO assets (
    kind, source_url, source_host, mime_type, byte_size, quality_label,
    delivery_policy, rights_status, attribution
) VALUES ($1, $2, $3, $4, $5, $6,
    CASE WHEN $7::rights_status = 'public_domain_verified'::rights_status THEN 'stream_proxy'::delivery_policy
         ELSE 'source_page_only'::delivery_policy END,
    $7::rights_status, $8)
ON CONFLICT (source_url) DO UPDATE
SET kind = EXCLUDED.kind, mime_type = EXCLUDED.mime_type,
    byte_size = EXCLUDED.byte_size, quality_label = EXCLUDED.quality_label,
    delivery_policy = EXCLUDED.delivery_policy,
    rights_status = EXCLUDED.rights_status,
    attribution = EXCLUDED.attribution,
    updated_at = now()
RETURNING id, kind, source_url, source_host, mime_type, byte_size, duration_seconds, width, height, quality_label, checksum, delivery_policy, rights_status, attribution, object_key, availability, created_at, updated_at
`

type UpsertAssetParams struct {
	Kind         string       `json:"kind"`
	SourceUrl    string       `json:"source_url"`
	SourceHost   string       `json:"source_host"`
	MimeType     pgtype.Text  `json:"mime_type"`
	ByteSize     pgtype.Int8  `json:"byte_size"`
	QualityLabel pgtype.Text  `json:"quality_label"`
	Column7      RightsStatus `json:"column_7"`
	Attribution  string       `json:"attribution"`
}

func (q *Queries) UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, upsertAsset,
		arg.Kind,
		arg.SourceUrl,
		arg.SourceHost,
		arg.MimeType,
		arg.ByteSize,
		arg.QualityLabel,
		arg.Column7,
		arg.Attribution,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SourceUrl,
		&i.SourceHost,
		&i.MimeType,
		&i.ByteSize,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.QualityLabel,
		&i.Checksum,
		&i.DeliveryPolicy,
		&i.RightsStatus,
		&i.Attribution,
		&i.ObjectKey,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContent = `-- name: UpsertContent :one
INSERT INTO contents (
    source_item_id, slug, type, title, level, published_at, body_blocks,
    rights_status, attribution, status, source_updated_at, released_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::rights_status, $9,
    CASE WHEN $8::rights_status = 'public_domain_verified'::rights_status THEN 'published'::content_status ELSE 'review'::content_status END,
    $6,
    CASE WHEN $8::rights_status = 'public_domain_verified'::rights_status THEN now() ELSE NULL END)
ON CONFLICT (source_item_id) DO UPDATE
SET title = EXCLUDED.title,
    type = EXCLUDED.type,
    level = EXCLUDED.level,
    published_at = EXCLUDED.published_at,
    body_blocks = EXCLUDED.body_blocks,
    rights_status = EXCLUDED.rights_status,
    attribution = EXCLUDED.attribution,
    status = CASE WHEN EXCLUDED.rights_status = 'public_domain_verified'
                  THEN 'published'::content_status ELSE 'review'::content_status END,
    released_at = CASE
        WHEN contents.status <> 'published'::content_status
             AND EXCLUDED.status = 'published'::content_status THEN now()
        ELSE contents.released_at
    END,
    source_updated_at = EXCLUDED.source_updated_at,
    revision = contents.revision + 1,
    updated_at = now()
RETURNING id, source_item_id, slug, type, title, summary, level, published_at, duration_seconds, body_blocks, transcript_blocks, metadata, rights_status, attribution, status, revision, source_updated_at, created_at, updated_at, released_at
`

type UpsertContentParams struct {
	SourceItemID uuid.UUID          `json:"source_item_id"`
	Slug         string             `json:"slug"`
	Type         ContentType        `json:"type"`
	Title        string             `json:"title"`
	Level        pgtype.Text        `json:"level"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	BodyBlocks   []byte             `json:"body_blocks"`
	Column8      RightsStatus       `json:"column_8"`
	Attribution  string             `json:"attribution"`
}

func (q *Queries) UpsertContent(ctx context.Context, arg UpsertContentParams) (Content, error) {
	row := q.db.QueryRow(ctx, upsertContent,
		arg.SourceItemID,
		arg.Slug,
		arg.Type,
		arg.Title,
		arg.Level,
		arg.PublishedAt,
		arg.BodyBlocks,
		arg.Column8,
		arg.Attribution,
	)
	var i Content
	err := row.Scan(
		&i.ID,
		&i.SourceItemID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Level,
		&i.PublishedAt,
		&i.DurationSeconds,
		&i.BodyBlocks,
		&i.TranscriptBlocks,
		&i.Metadata,
		&i.RightsStatus,
		&i.Attribution,
		&i.Status,
		&i.Revision,
		&i.SourceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}
