// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dictionary.sql

package dbgen

import (
	"context"
)

const listDictionaryFormLemmas = `-- name: ListDictionaryFormLemmas :many
SELECT lemma FROM dictionary_forms
WHERE form = $1
ORDER BY lemma
`

func (q *Queries) ListDictionaryFormLemmas(ctx context.Context, form string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDictionaryFormLemmas, form)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var lemma string
		if err := rows.Scan(&lemma); err != nil {
			return nil, err
		}
		items = append(items, lemma)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupDictionaryEntries = `-- name: LookupDictionaryEntries :many
SELECT id, normalized_word, word, part_of_speech, definition, examples, source, source_reference, sense_rank, content_id, created_at, updated_at FROM dictionary_entries
WHERE normalized_word = ANY($1::text[])
ORDER BY
    array_position($1::text[], normalized_word),
    sense_rank,
    part_of_speech,
    id
LIMIT 16
`

func (q *Queries) LookupDictionaryEntries(ctx context.Context, words []string) ([]DictionaryEntry, error) {
	rows, err := q.db.Query(ctx, lookupDictionaryEntries, words)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DictionaryEntry{}
	for rows.Next() {
		var i DictionaryEntry
		if err := rows.Scan(
			&i.ID,
			&i.NormalizedWord,
			&i.Word,
			&i.PartOfSpeech,
			&i.Definition,
			&i.Examples,
			&i.Source,
			&i.SourceReference,
			&i.SenseRank,
			&i.ContentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
