// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUserEvent = `-- name: CreateUserEvent :one
INSERT INTO user_events (user_id, entity_type, entity_id, operation)
VALUES ($1, $2, $3, $4) RETURNING sequence
`

type CreateUserEventParams struct {
	UserID     uuid.UUID `json:"user_id"`
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
	Operation  string    `json:"operation"`
}

func (q *Queries) CreateUserEvent(ctx context.Context, arg CreateUserEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserEvent,
		arg.UserID,
		arg.EntityType,
		arg.EntityID,
		arg.Operation,
	)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const deleteBookmark = `-- name: DeleteBookmark :exec
DELETE FROM bookmarks WHERE user_id = $1 AND content_id = $2
`

type DeleteBookmarkParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ContentID uuid.UUID `json:"content_id"`
}

func (q *Queries) DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error {
	_, err := q.db.Exec(ctx, deleteBookmark, arg.UserID, arg.ContentID)
	return err
}

const deleteRetellAttempt = `-- name: DeleteRetellAttempt :one
DELETE FROM retell_attempts WHERE user_id = $1 AND id = $2
RETURNING object_key
`

type DeleteRetellAttemptParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteRetellAttempt(ctx context.Context, arg DeleteRetellAttemptParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteRetellAttempt, arg.UserID, arg.ID)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteVocabularyEntry = `-- name: DeleteVocabularyEntry :exec
DELETE FROM vocabulary_entries WHERE user_id = $1 AND id = $2
`

type DeleteVocabularyEntryParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteVocabularyEntry(ctx context.Context, arg DeleteVocabularyEntryParams) error {
	_, err := q.db.Exec(ctx, deleteVocabularyEntry, arg.UserID, arg.ID)
	return err
}

const getRetellAttempt = `-- name: GetRetellAttempt :one
SELECT user_id, id, content_id, object_key, duration_milliseconds, byte_size, content_type, created_at, server_updated_at FROM retell_attempts WHERE user_id = $1 AND id = $2
`

type GetRetellAttemptParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetRetellAttempt(ctx context.Context, arg GetRetellAttemptParams) (RetellAttempt, error) {
	row := q.db.QueryRow(ctx, getRetellAttempt, arg.UserID, arg.ID)
	var i RetellAttempt
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.ContentID,
		&i.ObjectKey,
		&i.DurationMilliseconds,
		&i.ByteSize,
		&i.ContentType,
		&i.CreatedAt,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const getUserBySessionHash = `-- name: GetUserBySessionHash :one
SELECT u.id, u.apple_subject, u.created_at, u.updated_at FROM sessions s JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

func (q *Queries) GetUserBySessionHash(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySessionHash, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookmarks = `-- name: ListBookmarks :many
SELECT b.content_id, b.updated_at FROM bookmarks b
JOIN contents c ON c.id = b.content_id
WHERE b.user_id = $1 AND c.status = 'published'
ORDER BY b.updated_at DESC
`

type ListBookmarksRow struct {
	ContentID uuid.UUID          `json:"content_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListBookmarks(ctx context.Context, userID uuid.UUID) ([]ListBookmarksRow, error) {
	rows, err := q.db.Query(ctx, listBookmarks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookmarksRow{}
	for rows.Next() {
		var i ListBookmarksRow
		if err := rows.Scan(&i.ContentID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgress = `-- name: ListProgress :many
SELECT user_id, content_id, position_seconds, completed, client_updated_at, server_updated_at FROM learning_progress WHERE user_id = $1 ORDER BY server_updated_at DESC
`

func (q *Queries) ListProgress(ctx context.Context, userID uuid.UUID) ([]LearningProgress, error) {
	rows, err := q.db.Query(ctx, listProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LearningProgress{}
	for rows.Next() {
		var i LearningProgress
		if err := rows.Scan(
			&i.UserID,
			&i.ContentID,
			&i.PositionSeconds,
			&i.Completed,
			&i.ClientUpdatedAt,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetellAttempts = `-- name: ListRetellAttempts :many
SELECT user_id, id, content_id, object_key, duration_milliseconds, byte_size, content_type, created_at, server_updated_at FROM retell_attempts
WHERE user_id = $1
  AND ($2::uuid IS NULL OR content_id = $2)
ORDER BY created_at DESC
`

type ListRetellAttemptsParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	ContentID pgtype.UUID `json:"content_id"`
}

func (q *Queries) ListRetellAttempts(ctx context.Context, arg ListRetellAttemptsParams) ([]RetellAttempt, error) {
	rows, err := q.db.Query(ctx, listRetellAttempts, arg.UserID, arg.ContentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RetellAttempt{}
	for rows.Next() {
		var i RetellAttempt
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.ContentID,
			&i.ObjectKey,
			&i.DurationMilliseconds,
			&i.ByteSize,
			&i.ContentType,
			&i.CreatedAt,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEventsAfter = `-- name: ListUserEventsAfter :many
SELECT sequence, user_id, entity_type, entity_id, operation, created_at FROM user_events WHERE user_id = $1 AND sequence > $2 ORDER BY sequence LIMIT $3
`

type ListUserEventsAfterParams struct {
	UserID   uuid.UUID `json:"user_id"`
	Sequence int64     `json:"sequence"`
	Limit    int32     `json:"limit"`
}

func (q *Queries) ListUserEventsAfter(ctx context.Context, arg ListUserEventsAfterParams) ([]UserEvent, error) {
	rows, err := q.db.Query(ctx, listUserEventsAfter, arg.UserID, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserEvent{}
	for rows.Next() {
		var i UserEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.UserID,
			&i.EntityType,
			&i.EntityID,
			&i.Operation,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyEntries = `-- name: ListVocabularyEntries :many
SELECT id, user_id, word, normalized_word, definition, sentence_context, content_id, content_title, created_at, updated_at FROM vocabulary_entries
WHERE user_id = $1
ORDER BY updated_at DESC, word
`

func (q *Queries) ListVocabularyEntries(ctx context.Context, userID uuid.UUID) ([]VocabularyEntry, error) {
	rows, err := q.db.Query(ctx, listVocabularyEntries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VocabularyEntry{}
	for rows.Next() {
		var i VocabularyEntry
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Word,
			&i.NormalizedWord,
			&i.Definition,
			&i.SentenceContext,
			&i.ContentID,
			&i.ContentTitle,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAppleIdentityTokenUse = `-- name: RecordAppleIdentityTokenUse :exec
INSERT INTO apple_identity_token_uses (token_hash, user_id) VALUES ($1, $2)
`

type RecordAppleIdentityTokenUseParams struct {
	TokenHash []byte    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RecordAppleIdentityTokenUse(ctx context.Context, arg RecordAppleIdentityTokenUseParams) error {
	_, err := q.db.Exec(ctx, recordAppleIdentityTokenUse, arg.TokenHash, arg.UserID)
	return err
}

const upsertAppleUser = `-- name: UpsertAppleUser :one
INSERT INTO users (apple_subject) VALUES ($1)
ON CONFLICT (apple_subject) DO UPDATE SET updated_at = now()
RETURNING id, apple_subject, created_at, updated_at
`

func (q *Queries) UpsertAppleUser(ctx context.Context, appleSubject string) (User, error) {
	row := q.db.QueryRow(ctx, upsertAppleUser, appleSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AppleSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBookmark = `-- name: UpsertBookmark :exec
INSERT INTO bookmarks (user_id, content_id) VALUES ($1, $2)
ON CONFLICT (user_id, content_id) DO UPDATE SET updated_at = now()
`

type UpsertBookmarkParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ContentID uuid.UUID `json:"content_id"`
}

func (q *Queries) UpsertBookmark(ctx context.Context, arg UpsertBookmarkParams) error {
	_, err := q.db.Exec(ctx, upsertBookmark, arg.UserID, arg.ContentID)
	return err
}

const upsertProgress = `-- name: UpsertProgress :one
INSERT INTO learning_progress (user_id, content_id, position_seconds, completed, client_updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, content_id) DO UPDATE
SET position_seconds = CASE WHEN learning_progress.client_updated_at <= EXCLUDED.client_updated_at THEN EXCLUDED.position_seconds ELSE learning_progress.position_seconds END,
    completed = CASE WHEN learning_progress.client_updated_at <= EXCLUDED.client_updated_at THEN EXCLUDED.completed ELSE learning_progress.completed END,
    client_updated_at = GREATEST(learning_progress.client_updated_at, EXCLUDED.client_updated_at),
    server_updated_at = now()
RETURNING user_id, content_id, position_seconds, completed, client_updated_at, server_updated_at
`

type UpsertProgressParams struct {
	UserID          uuid.UUID          `json:"user_id"`
	ContentID       uuid.UUID          `json:"content_id"`
	PositionSeconds int32              `json:"position_seconds"`
	Completed       bool               `json:"completed"`
	ClientUpdatedAt pgtype.Timestamptz `json:"client_updated_at"`
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) (LearningProgress, error) {
	row := q.db.QueryRow(ctx, upsertProgress,
		arg.UserID,
		arg.ContentID,
		arg.PositionSeconds,
		arg.Completed,
		arg.ClientUpdatedAt,
	)
	var i LearningProgress
	err := row.Scan(
		&i.UserID,
		&i.ContentID,
		&i.PositionSeconds,
		&i.Completed,
		&i.ClientUpdatedAt,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const upsertRetellAttempt = `-- name: UpsertRetellAttempt :one
INSERT INTO retell_attempts (
    user_id, id, content_id, object_key, duration_milliseconds, byte_size, content_type, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, id) DO UPDATE
SET content_id = EXCLUDED.content_id,
    object_key = EXCLUDED.object_key,
    duration_milliseconds = EXCLUDED.duration_milliseconds,
    byte_size = EXCLUDED.byte_size,
    content_type = EXCLUDED.content_type,
    created_at = EXCLUDED.created_at,
    server_updated_at = now()
RETURNING user_id, id, content_id, object_key, duration_milliseconds, byte_size, content_type, created_at, server_updated_at
`

type UpsertRetellAttemptParams struct {
	UserID               uuid.UUID          `json:"user_id"`
	ID                   uuid.UUID          `json:"id"`
	ContentID            uuid.UUID          `json:"content_id"`
	ObjectKey            string             `json:"object_key"`
	DurationMilliseconds int32              `json:"duration_milliseconds"`
	ByteSize             int64              `json:"byte_size"`
	ContentType          string             `json:"content_type"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertRetellAttempt(ctx context.Context, arg UpsertRetellAttemptParams) (RetellAttempt, error) {
	row := q.db.QueryRow(ctx, upsertRetellAttempt,
		arg.UserID,
		arg.ID,
		arg.ContentID,
		arg.ObjectKey,
		arg.DurationMilliseconds,
		arg.ByteSize,
		arg.ContentType,
		arg.CreatedAt,
	)
	var i RetellAttempt
	err := row.Scan(
		&i.UserID,
		&i.ID,
		&i.ContentID,
		&i.ObjectKey,
		&i.DurationMilliseconds,
		&i.ByteSize,
		&i.ContentType,
		&i.CreatedAt,
		&i.ServerUpdatedAt,
	)
	return i, err
}

const upsertVocabularyEntry = `-- name: UpsertVocabularyEntry :one
INSERT INTO vocabulary_entries (
    id, user_id, word, normalized_word, definition, sentence_context,
    content_id, content_title, created_at
)
VALUES (
    $1, $2, $3, $4,
    NULLIF($5::text, ''),
    NULLIF($6::text, ''),
    $7,
    NULLIF($8::text, ''),
    $9
)
ON CONFLICT (user_id, normalized_word) DO UPDATE
SET word = EXCLUDED.word,
    definition = COALESCE(EXCLUDED.definition, vocabulary_entries.definition),
    sentence_context = COALESCE(EXCLUDED.sentence_context, vocabulary_entries.sentence_context),
    content_id = COALESCE(EXCLUDED.content_id, vocabulary_entries.content_id),
    content_title = COALESCE(EXCLUDED.content_title, vocabulary_entries.content_title),
    created_at = LEAST(vocabulary_entries.created_at, EXCLUDED.created_at),
    updated_at = now()
RETURNING id, user_id, word, normalized_word, definition, sentence_context, content_id, content_title, created_at, updated_at
`

type UpsertVocabularyEntryParams struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Word            string             `json:"word"`
	NormalizedWord  string             `json:"normalized_word"`
	Definition      string             `json:"definition"`
	SentenceContext string             `json:"sentence_context"`
	ContentID       pgtype.UUID        `json:"content_id"`
	ContentTitle    string             `json:"content_title"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertVocabularyEntry(ctx context.Context, arg UpsertVocabularyEntryParams) (VocabularyEntry, error) {
	row := q.db.QueryRow(ctx, upsertVocabularyEntry,
		arg.ID,
		arg.UserID,
		arg.Word,
		arg.NormalizedWord,
		arg.Definition,
		arg.SentenceContext,
		arg.ContentID,
		arg.ContentTitle,
		arg.CreatedAt,
	)
	var i VocabularyEntry
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Word,
		&i.NormalizedWord,
		&i.Definition,
		&i.SentenceContext,
		&i.ContentID,
		&i.ContentTitle,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
