// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContentStatus string

const (
	ContentStatusDraft     ContentStatus = "draft"
	ContentStatusReview    ContentStatus = "review"
	ContentStatusPublished ContentStatus = "published"
	ContentStatusHidden    ContentStatus = "hidden"
	ContentStatusRemoved   ContentStatus = "removed"
)

func (e *ContentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentStatus(s)
	case string:
		*e = ContentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentStatus: %T", src)
	}
	return nil
}

type NullContentStatus struct {
	ContentStatus ContentStatus `json:"content_status"`
	Valid         bool          `json:"valid"` // Valid is true if ContentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentStatus), nil
}

type ContentType string

const (
	ContentTypeArticle ContentType = "article"
	ContentTypeLesson  ContentType = "lesson"
	ContentTypePodcast ContentType = "podcast"
	ContentTypeVideo   ContentType = "video"
	ContentTypeQuiz    ContentType = "quiz"
)

func (e *ContentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContentType(s)
	case string:
		*e = ContentType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContentType: %T", src)
	}
	return nil
}

type NullContentType struct {
	ContentType ContentType `json:"content_type"`
	Valid       bool        `json:"valid"` // Valid is true if ContentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContentType) Scan(value interface{}) error {
	if value == nil {
		ns.ContentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContentType), nil
}

type DeliveryPolicy string

const (
	DeliveryPolicyStreamProxy    DeliveryPolicy = "stream_proxy"
	DeliveryPolicyRedirect       DeliveryPolicy = "redirect"
	DeliveryPolicyManagedCache   DeliveryPolicy = "managed_cache"
	DeliveryPolicySourcePageOnly DeliveryPolicy = "source_page_only"
)

func (e *DeliveryPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryPolicy(s)
	case string:
		*e = DeliveryPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryPolicy: %T", src)
	}
	return nil
}

type NullDeliveryPolicy struct {
	DeliveryPolicy DeliveryPolicy `json:"delivery_policy"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryPolicy), nil
}

type RightsStatus string

const (
	RightsStatusUnknown              RightsStatus = "unknown"
	RightsStatusReviewRequired       RightsStatus = "review_required"
	RightsStatusPublicDomainVerified RightsStatus = "public_domain_verified"
	RightsStatusThirdPartyRestricted RightsStatus = "third_party_restricted"
)

func (e *RightsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RightsStatus(s)
	case string:
		*e = RightsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RightsStatus: %T", src)
	}
	return nil
}

type NullRightsStatus struct {
	RightsStatus RightsStatus `json:"rights_status"`
	Valid        bool         `json:"valid"` // Valid is true if RightsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRightsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RightsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RightsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRightsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RightsStatus), nil
}

type SourceFetchState string

const (
	SourceFetchStateDiscovered SourceFetchState = "discovered"
	SourceFetchStateScheduled  SourceFetchState = "scheduled"
	SourceFetchStateFetched    SourceFetchState = "fetched"
	SourceFetchStateFailed     SourceFetchState = "failed"
	SourceFetchStateDisabled   SourceFetchState = "disabled"
)

func (e *SourceFetchState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceFetchState(s)
	case string:
		*e = SourceFetchState(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceFetchState: %T", src)
	}
	return nil
}

type NullSourceFetchState struct {
	SourceFetchState SourceFetchState `json:"source_fetch_state"`
	Valid            bool             `json:"valid"` // Valid is true if SourceFetchState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceFetchState) Scan(value interface{}) error {
	if value == nil {
		ns.SourceFetchState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceFetchState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceFetchState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceFetchState), nil
}

type AppleIdentityTokenUse struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

type Asset struct {
	ID              uuid.UUID          `json:"id"`
	Kind            string             `json:"kind"`
	SourceUrl       string             `json:"source_url"`
	SourceHost      string             `json:"source_host"`
	MimeType        pgtype.Text        `json:"mime_type"`
	ByteSize        pgtype.Int8        `json:"byte_size"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Width           pgtype.Int4        `json:"width"`
	Height          pgtype.Int4        `json:"height"`
	QualityLabel    pgtype.Text        `json:"quality_label"`
	Checksum        pgtype.Text        `json:"checksum"`
	DeliveryPolicy  DeliveryPolicy     `json:"delivery_policy"`
	RightsStatus    RightsStatus       `json:"rights_status"`
	Attribution     string             `json:"attribution"`
	ObjectKey       pgtype.Text        `json:"object_key"`
	Availability    string             `json:"availability"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Bookmark struct {
	UserID    uuid.UUID          `json:"user_id"`
	ContentID uuid.UUID          `json:"content_id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID        uuid.UUID   `json:"id"`
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	Kind      string      `json:"kind"`
	ParentID  pgtype.UUID `json:"parent_id"`
	SortOrder int32       `json:"sort_order"`
	Status    string      `json:"status"`
}

type Content struct {
	ID               uuid.UUID          `json:"id"`
	SourceItemID     uuid.UUID          `json:"source_item_id"`
	Slug             string             `json:"slug"`
	Type             ContentType        `json:"type"`
	Title            string             `json:"title"`
	Summary          pgtype.Text        `json:"summary"`
	Level            pgtype.Text        `json:"level"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	BodyBlocks       []byte             `json:"body_blocks"`
	TranscriptBlocks []byte             `json:"transcript_blocks"`
	Metadata         []byte             `json:"metadata"`
	RightsStatus     RightsStatus       `json:"rights_status"`
	Attribution      string             `json:"attribution"`
	Status           ContentStatus      `json:"status"`
	Revision         int32              `json:"revision"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ContentAsset struct {
	ContentID uuid.UUID `json:"content_id"`
	AssetID   uuid.UUID `json:"asset_id"`
	Role      string    `json:"role"`
	Position  int32     `json:"position"`
}

type ContentCategory struct {
	ContentID  uuid.UUID `json:"content_id"`
	CategoryID uuid.UUID `json:"category_id"`
	IsPrimary  bool      `json:"is_primary"`
	Position   int32     `json:"position"`
}

type ContentSeries struct {
	ContentID uuid.UUID `json:"content_id"`
	SeriesID  uuid.UUID `json:"series_id"`
	Position  int32     `json:"position"`
}

type LearningProgress struct {
	UserID          uuid.UUID          `json:"user_id"`
	ContentID       uuid.UUID          `json:"content_id"`
	PositionSeconds int32              `json:"position_seconds"`
	Completed       bool               `json:"completed"`
	ClientUpdatedAt pgtype.Timestamptz `json:"client_updated_at"`
	ServerUpdatedAt pgtype.Timestamptz `json:"server_updated_at"`
}

type PublishEvent struct {
	Sequence    int64              `json:"sequence"`
	EntityType  string             `json:"entity_type"`
	EntityID    uuid.UUID          `json:"entity_id"`
	Operation   string             `json:"operation"`
	Revision    pgtype.Int4        `json:"revision"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type RetellAttempt struct {
	UserID               uuid.UUID          `json:"user_id"`
	ID                   uuid.UUID          `json:"id"`
	ContentID            uuid.UUID          `json:"content_id"`
	ObjectKey            string             `json:"object_key"`
	DurationMilliseconds int32              `json:"duration_milliseconds"`
	ByteSize             int64              `json:"byte_size"`
	ContentType          string             `json:"content_type"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ServerUpdatedAt      pgtype.Timestamptz `json:"server_updated_at"`
}

type Series struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Level        pgtype.Text        `json:"level"`
	SourceItemID pgtype.UUID        `json:"source_item_id"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SourceItem struct {
	ID           uuid.UUID          `json:"id"`
	Source       string             `json:"source"`
	CanonicalUrl string             `json:"canonical_url"`
	ExternalID   pgtype.Text        `json:"external_id"`
	PageType     pgtype.Text        `json:"page_type"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	FetchState   SourceFetchState   `json:"fetch_state"`
	NextFetchAt  pgtype.Timestamptz `json:"next_fetch_at"`
}

type SourceSnapshot struct {
	ID            uuid.UUID          `json:"id"`
	SourceItemID  uuid.UUID          `json:"source_item_id"`
	FetchedAt     pgtype.Timestamptz `json:"fetched_at"`
	HttpStatus    int32              `json:"http_status"`
	Etag          pgtype.Text        `json:"etag"`
	LastModified  pgtype.Text        `json:"last_modified"`
	ContentHash   string             `json:"content_hash"`
	ObjectKey     string             `json:"object_key"`
	ParserVersion pgtype.Text        `json:"parser_version"`
	ParseState    string             `json:"parse_state"`
	ErrorCode     pgtype.Text        `json:"error_code"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	AppleSubject string             `json:"apple_subject"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserEvent struct {
	Sequence   int64              `json:"sequence"`
	UserID     uuid.UUID          `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   uuid.UUID          `json:"entity_id"`
	Operation  string             `json:"operation"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type VocabularyEntry struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Word            string             `json:"word"`
	NormalizedWord  string             `json:"normalized_word"`
	Definition      pgtype.Text        `json:"definition"`
	SentenceContext pgtype.Text        `json:"sentence_context"`
	ContentID       pgtype.UUID        `json:"content_id"`
	ContentTitle    pgtype.Text        `json:"content_title"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
