// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDeliverableAsset = `-- name: GetDeliverableAsset :one
SELECT id, kind, source_url, source_host, mime_type, byte_size, duration_seconds, width, height, quality_label, checksum, delivery_policy, rights_status, attribution, object_key, availability, created_at, updated_at FROM assets
WHERE id = $1 AND availability = 'available'
  AND ((rights_status = 'public_domain_verified' AND delivery_policy = 'stream_proxy')
       OR (delivery_policy = 'managed_cache' AND object_key IS NOT NULL))
`

func (q *Queries) GetDeliverableAsset(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getDeliverableAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SourceUrl,
		&i.SourceHost,
		&i.MimeType,
		&i.ByteSize,
		&i.DurationSeconds,
		&i.Width,
		&i.Height,
		&i.QualityLabel,
		&i.Checksum,
		&i.DeliveryPolicy,
		&i.RightsStatus,
		&i.Attribution,
		&i.ObjectKey,
		&i.Availability,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedContent = `-- name: GetPublishedContent :one
SELECT c.id, c.source_item_id, c.slug, c.type, c.title, c.summary, c.level, c.published_at, c.duration_seconds, c.body_blocks, c.transcript_blocks, c.metadata, c.rights_status, c.attribution, c.status, c.revision, c.source_updated_at, c.created_at, c.updated_at, c.released_at, s.canonical_url
FROM contents c JOIN source_items s ON s.id = c.source_item_id
WHERE c.id = $1 AND c.status = 'published'
  AND EXISTS (
    SELECT 1 FROM content_assets ca
    JOIN assets a ON a.id = ca.asset_id
    WHERE ca.content_id = c.id AND a.kind = 'audio'
      AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
`

type GetPublishedContentRow struct {
	ID               uuid.UUID          `json:"id"`
	SourceItemID     uuid.UUID          `json:"source_item_id"`
	Slug             string             `json:"slug"`
	Type             ContentType        `json:"type"`
	Title            string             `json:"title"`
	Summary          pgtype.Text        `json:"summary"`
	Level            pgtype.Text        `json:"level"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	BodyBlocks       []byte             `json:"body_blocks"`
	TranscriptBlocks []byte             `json:"transcript_blocks"`
	Metadata         []byte             `json:"metadata"`
	RightsStatus     RightsStatus       `json:"rights_status"`
	Attribution      string             `json:"attribution"`
	Status           ContentStatus      `json:"status"`
	Revision         int32              `json:"revision"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	CanonicalUrl     string             `json:"canonical_url"`
}

func (q *Queries) GetPublishedContent(ctx context.Context, id uuid.UUID) (GetPublishedContentRow, error) {
	row := q.db.QueryRow(ctx, getPublishedContent, id)
	var i GetPublishedContentRow
	err := row.Scan(
		&i.ID,
		&i.SourceItemID,
		&i.Slug,
		&i.Type,
		&i.Title,
		&i.Summary,
		&i.Level,
		&i.PublishedAt,
		&i.DurationSeconds,
		&i.BodyBlocks,
		&i.TranscriptBlocks,
		&i.Metadata,
		&i.RightsStatus,
		&i.Attribution,
		&i.Status,
		&i.Revision,
		&i.SourceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
		&i.CanonicalUrl,
	)
	return i, err
}

const getSeries = `-- name: GetSeries :one
SELECT s.id, s.slug, s.title, s.description, s.level, s.source_item_id, s.status, s.created_at, s.updated_at FROM series s
WHERE s.id = $1 AND s.status = 'active'
  AND EXISTS (
    SELECT 1 FROM content_series cs
    JOIN contents c ON c.id = cs.content_id
    JOIN content_assets ca ON ca.content_id = c.id
    JOIN assets a ON a.id = ca.asset_id
    WHERE cs.series_id = s.id AND c.status = 'published' AND a.kind = 'audio'
      AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
`

func (q *Queries) GetSeries(ctx context.Context, id uuid.UUID) (Series, error) {
	row := q.db.QueryRow(ctx, getSeries, id)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.SourceItemID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkContentCategoryBySlug = `-- name: LinkContentCategoryBySlug :exec
INSERT INTO content_categories (content_id, category_id, is_primary)
SELECT $1, id, true FROM categories WHERE slug = $2
ON CONFLICT (content_id, category_id) DO UPDATE SET is_primary = true
`

type LinkContentCategoryBySlugParams struct {
	ContentID uuid.UUID `json:"content_id"`
	Slug      string    `json:"slug"`
}

func (q *Queries) LinkContentCategoryBySlug(ctx context.Context, arg LinkContentCategoryBySlugParams) error {
	_, err := q.db.Exec(ctx, linkContentCategoryBySlug, arg.ContentID, arg.Slug)
	return err
}

const linkContentSeries = `-- name: LinkContentSeries :exec
INSERT INTO content_series (content_id, series_id, position) VALUES ($1, $2, $3)
ON CONFLICT (content_id) DO UPDATE SET series_id = EXCLUDED.series_id, position = EXCLUDED.position
`

type LinkContentSeriesParams struct {
	ContentID uuid.UUID `json:"content_id"`
	SeriesID  uuid.UUID `json:"series_id"`
	Position  int32     `json:"position"`
}

func (q *Queries) LinkContentSeries(ctx context.Context, arg LinkContentSeriesParams) error {
	_, err := q.db.Exec(ctx, linkContentSeries, arg.ContentID, arg.SeriesID, arg.Position)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT cat.id, cat.slug, cat.name, cat.kind, cat.parent_id, cat.sort_order, cat.status FROM categories cat
WHERE cat.status = 'active'
  AND EXISTS (
    SELECT 1 FROM content_categories cc
    JOIN contents c ON c.id = cc.content_id
    JOIN content_assets ca ON ca.content_id = c.id
    JOIN assets a ON a.id = ca.asset_id
    WHERE cc.category_id = cat.id AND c.status = 'published'
      AND a.kind = 'audio' AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
ORDER BY cat.sort_order, cat.name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.ParentID,
			&i.SortOrder,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryContents = `-- name: ListCategoryContents :many
SELECT c.id, c.source_item_id, c.slug, c.type, c.title, c.summary, c.level, c.published_at, c.duration_seconds, c.body_blocks, c.transcript_blocks, c.metadata, c.rights_status, c.attribution, c.status, c.revision, c.source_updated_at, c.created_at, c.updated_at, c.released_at, s.canonical_url
FROM content_categories cc
JOIN categories cat ON cat.id = cc.category_id
JOIN contents c ON c.id = cc.content_id
JOIN source_items s ON s.id = c.source_item_id
WHERE cat.slug = $1 AND c.status = 'published'
  AND EXISTS (
    SELECT 1 FROM content_assets playable_ca
    JOIN assets playable ON playable.id = playable_ca.asset_id
    WHERE playable_ca.content_id = c.id AND playable.kind = 'audio'
      AND playable.delivery_policy = 'managed_cache' AND playable.availability = 'available'
  )
ORDER BY c.published_at DESC NULLS LAST, c.id DESC
LIMIT $2
`

type ListCategoryContentsParams struct {
	Slug  string `json:"slug"`
	Limit int32  `json:"limit"`
}

type ListCategoryContentsRow struct {
	ID               uuid.UUID          `json:"id"`
	SourceItemID     uuid.UUID          `json:"source_item_id"`
	Slug             string             `json:"slug"`
	Type             ContentType        `json:"type"`
	Title            string             `json:"title"`
	Summary          pgtype.Text        `json:"summary"`
	Level            pgtype.Text        `json:"level"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	BodyBlocks       []byte             `json:"body_blocks"`
	TranscriptBlocks []byte             `json:"transcript_blocks"`
	Metadata         []byte             `json:"metadata"`
	RightsStatus     RightsStatus       `json:"rights_status"`
	Attribution      string             `json:"attribution"`
	Status           ContentStatus      `json:"status"`
	Revision         int32              `json:"revision"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	CanonicalUrl     string             `json:"canonical_url"`
}

func (q *Queries) ListCategoryContents(ctx context.Context, arg ListCategoryContentsParams) ([]ListCategoryContentsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryContents, arg.Slug, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoryContentsRow{}
	for rows.Next() {
		var i ListCategoryContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceItemID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Level,
			&i.PublishedAt,
			&i.DurationSeconds,
			&i.BodyBlocks,
			&i.TranscriptBlocks,
			&i.Metadata,
			&i.RightsStatus,
			&i.Attribution,
			&i.Status,
			&i.Revision,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
			&i.CanonicalUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentAssets = `-- name: ListContentAssets :many
SELECT a.id, a.kind, a.source_url, a.source_host, a.mime_type, a.byte_size, a.duration_seconds, a.width, a.height, a.quality_label, a.checksum, a.delivery_policy, a.rights_status, a.attribution, a.object_key, a.availability, a.created_at, a.updated_at, ca.role, ca.position
FROM content_assets ca JOIN assets a ON a.id = ca.asset_id
WHERE ca.content_id = $1
ORDER BY ca.position, a.id
`

type ListContentAssetsRow struct {
	ID              uuid.UUID          `json:"id"`
	Kind            string             `json:"kind"`
	SourceUrl       string             `json:"source_url"`
	SourceHost      string             `json:"source_host"`
	MimeType        pgtype.Text        `json:"mime_type"`
	ByteSize        pgtype.Int8        `json:"byte_size"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Width           pgtype.Int4        `json:"width"`
	Height          pgtype.Int4        `json:"height"`
	QualityLabel    pgtype.Text        `json:"quality_label"`
	Checksum        pgtype.Text        `json:"checksum"`
	DeliveryPolicy  DeliveryPolicy     `json:"delivery_policy"`
	RightsStatus    RightsStatus       `json:"rights_status"`
	Attribution     string             `json:"attribution"`
	ObjectKey       pgtype.Text        `json:"object_key"`
	Availability    string             `json:"availability"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Role            string             `json:"role"`
	Position        int32              `json:"position"`
}

func (q *Queries) ListContentAssets(ctx context.Context, contentID uuid.UUID) ([]ListContentAssetsRow, error) {
	rows, err := q.db.Query(ctx, listContentAssets, contentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentAssetsRow{}
	for rows.Next() {
		var i ListContentAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SourceUrl,
			&i.SourceHost,
			&i.MimeType,
			&i.ByteSize,
			&i.DurationSeconds,
			&i.Width,
			&i.Height,
			&i.QualityLabel,
			&i.Checksum,
			&i.DeliveryPolicy,
			&i.RightsStatus,
			&i.Attribution,
			&i.ObjectKey,
			&i.Availability,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishEventsAfter = `-- name: ListPublishEventsAfter :many
SELECT pe.sequence, pe.entity_type, pe.entity_id, pe.operation, pe.revision, pe.published_at FROM publish_events pe
WHERE pe.sequence > $1 AND pe.entity_type = 'content'
  AND EXISTS (
    SELECT 1 FROM contents c
    JOIN content_assets ca ON ca.content_id = c.id
    JOIN assets a ON a.id = ca.asset_id
    WHERE c.id = pe.entity_id AND c.status = 'published' AND a.kind = 'audio'
      AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
ORDER BY pe.sequence LIMIT $2
`

type ListPublishEventsAfterParams struct {
	Sequence int64 `json:"sequence"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListPublishEventsAfter(ctx context.Context, arg ListPublishEventsAfterParams) ([]PublishEvent, error) {
	rows, err := q.db.Query(ctx, listPublishEventsAfter, arg.Sequence, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishEvent{}
	for rows.Next() {
		var i PublishEvent
		if err := rows.Scan(
			&i.Sequence,
			&i.EntityType,
			&i.EntityID,
			&i.Operation,
			&i.Revision,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedContents = `-- name: ListPublishedContents :many
SELECT c.id, c.source_item_id, c.slug, c.type, c.title, c.summary, c.level, c.published_at, c.duration_seconds, c.body_blocks, c.transcript_blocks, c.metadata, c.rights_status, c.attribution, c.status, c.revision, c.source_updated_at, c.created_at, c.updated_at, c.released_at, s.canonical_url
FROM contents c JOIN source_items s ON s.id = c.source_item_id
WHERE c.status = 'published'
  AND EXISTS (
    SELECT 1 FROM content_assets ca
    JOIN assets a ON a.id = ca.asset_id
    WHERE ca.content_id = c.id AND a.kind = 'audio'
      AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
  AND ($1::timestamptz IS NULL
       OR (c.released_at, c.id) < ($1::timestamptz, $2::uuid))
ORDER BY c.released_at DESC NULLS LAST, c.id DESC
LIMIT $3
`

type ListPublishedContentsParams struct {
	BeforeReleasedAt pgtype.Timestamptz `json:"before_released_at"`
	BeforeID         pgtype.UUID        `json:"before_id"`
	PageLimit        int32              `json:"page_limit"`
}

type ListPublishedContentsRow struct {
	ID               uuid.UUID          `json:"id"`
	SourceItemID     uuid.UUID          `json:"source_item_id"`
	Slug             string             `json:"slug"`
	Type             ContentType        `json:"type"`
	Title            string             `json:"title"`
	Summary          pgtype.Text        `json:"summary"`
	Level            pgtype.Text        `json:"level"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	BodyBlocks       []byte             `json:"body_blocks"`
	TranscriptBlocks []byte             `json:"transcript_blocks"`
	Metadata         []byte             `json:"metadata"`
	RightsStatus     RightsStatus       `json:"rights_status"`
	Attribution      string             `json:"attribution"`
	Status           ContentStatus      `json:"status"`
	Revision         int32              `json:"revision"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	CanonicalUrl     string             `json:"canonical_url"`
}

func (q *Queries) ListPublishedContents(ctx context.Context, arg ListPublishedContentsParams) ([]ListPublishedContentsRow, error) {
	rows, err := q.db.Query(ctx, listPublishedContents, arg.BeforeReleasedAt, arg.BeforeID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedContentsRow{}
	for rows.Next() {
		var i ListPublishedContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceItemID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Level,
			&i.PublishedAt,
			&i.DurationSeconds,
			&i.BodyBlocks,
			&i.TranscriptBlocks,
			&i.Metadata,
			&i.RightsStatus,
			&i.Attribution,
			&i.Status,
			&i.Revision,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
			&i.CanonicalUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeries = `-- name: ListSeries :many
SELECT s.id, s.slug, s.title, s.description, s.level, s.source_item_id, s.status, s.created_at, s.updated_at FROM series s
WHERE s.status = 'active'
  AND EXISTS (
    SELECT 1 FROM content_series cs
    JOIN contents c ON c.id = cs.content_id
    JOIN content_assets ca ON ca.content_id = c.id
    JOIN assets a ON a.id = ca.asset_id
    WHERE cs.series_id = s.id AND c.status = 'published' AND a.kind = 'audio'
      AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
ORDER BY s.title LIMIT $1
`

func (q *Queries) ListSeries(ctx context.Context, limit int32) ([]Series, error) {
	rows, err := q.db.Query(ctx, listSeries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Series{}
	for rows.Next() {
		var i Series
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.SourceItemID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeriesContents = `-- name: ListSeriesContents :many
SELECT c.id, c.source_item_id, c.slug, c.type, c.title, c.summary, c.level, c.published_at, c.duration_seconds, c.body_blocks, c.transcript_blocks, c.metadata, c.rights_status, c.attribution, c.status, c.revision, c.source_updated_at, c.created_at, c.updated_at, c.released_at, s.canonical_url, cs.position
FROM content_series cs
JOIN contents c ON c.id = cs.content_id
JOIN source_items s ON s.id = c.source_item_id
WHERE cs.series_id = $1 AND c.status = 'published'
  AND EXISTS (
    SELECT 1 FROM content_assets playable_ca
    JOIN assets playable ON playable.id = playable_ca.asset_id
    WHERE playable_ca.content_id = c.id AND playable.kind = 'audio'
      AND playable.delivery_policy = 'managed_cache' AND playable.availability = 'available'
  )
ORDER BY cs.position, c.published_at, c.id
`

type ListSeriesContentsRow struct {
	ID               uuid.UUID          `json:"id"`
	SourceItemID     uuid.UUID          `json:"source_item_id"`
	Slug             string             `json:"slug"`
	Type             ContentType        `json:"type"`
	Title            string             `json:"title"`
	Summary          pgtype.Text        `json:"summary"`
	Level            pgtype.Text        `json:"level"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	BodyBlocks       []byte             `json:"body_blocks"`
	TranscriptBlocks []byte             `json:"transcript_blocks"`
	Metadata         []byte             `json:"metadata"`
	RightsStatus     RightsStatus       `json:"rights_status"`
	Attribution      string             `json:"attribution"`
	Status           ContentStatus      `json:"status"`
	Revision         int32              `json:"revision"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	CanonicalUrl     string             `json:"canonical_url"`
	Position         int32              `json:"position"`
}

func (q *Queries) ListSeriesContents(ctx context.Context, seriesID uuid.UUID) ([]ListSeriesContentsRow, error) {
	rows, err := q.db.Query(ctx, listSeriesContents, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeriesContentsRow{}
	for rows.Next() {
		var i ListSeriesContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceItemID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Level,
			&i.PublishedAt,
			&i.DurationSeconds,
			&i.BodyBlocks,
			&i.TranscriptBlocks,
			&i.Metadata,
			&i.RightsStatus,
			&i.Attribution,
			&i.Status,
			&i.Revision,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
			&i.CanonicalUrl,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPublishedContents = `-- name: SearchPublishedContents :many
SELECT c.id, c.source_item_id, c.slug, c.type, c.title, c.summary, c.level, c.published_at, c.duration_seconds, c.body_blocks, c.transcript_blocks, c.metadata, c.rights_status, c.attribution, c.status, c.revision, c.source_updated_at, c.created_at, c.updated_at, c.released_at, s.canonical_url,
       ts_rank(
         to_tsvector('english', coalesce(c.title, '') || ' ' || coalesce(c.summary, '') || ' ' || coalesce(c.body_blocks::text, '') || ' ' || coalesce(c.metadata::text, '')),
         websearch_to_tsquery('english', $1)
       ) AS rank
FROM contents c JOIN source_items s ON s.id = c.source_item_id
WHERE c.status = 'published'
  AND EXISTS (
    SELECT 1 FROM content_assets ca
    JOIN assets a ON a.id = ca.asset_id
    WHERE ca.content_id = c.id AND a.kind = 'audio'
      AND a.delivery_policy = 'managed_cache' AND a.availability = 'available'
  )
  AND (
    to_tsvector('english', coalesce(c.title, '') || ' ' || coalesce(c.summary, '') || ' ' || coalesce(c.body_blocks::text, '') || ' ' || coalesce(c.metadata::text, '')) @@ websearch_to_tsquery('english', $1)
    OR lower(c.title) LIKE '%' || lower($1) || '%'
    OR lower(coalesce(c.summary, '')) LIKE '%' || lower($1) || '%'
    OR lower(c.body_blocks::text) LIKE '%' || lower($1) || '%'
    OR lower(c.metadata::text) LIKE '%' || lower($1) || '%'
  )
ORDER BY
  CASE
    WHEN lower(c.title) = lower($1) THEN 4
    WHEN lower(c.title) LIKE lower($1) || '%' THEN 3
    WHEN lower(c.title) LIKE '%' || lower($1) || '%' THEN 2
    ELSE 1
  END DESC,
  rank DESC,
  c.published_at DESC NULLS LAST
LIMIT $2
`

type SearchPublishedContentsParams struct {
	SearchQuery string `json:"search_query"`
	PageLimit   int32  `json:"page_limit"`
}

type SearchPublishedContentsRow struct {
	ID               uuid.UUID          `json:"id"`
	SourceItemID     uuid.UUID          `json:"source_item_id"`
	Slug             string             `json:"slug"`
	Type             ContentType        `json:"type"`
	Title            string             `json:"title"`
	Summary          pgtype.Text        `json:"summary"`
	Level            pgtype.Text        `json:"level"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DurationSeconds  pgtype.Int4        `json:"duration_seconds"`
	BodyBlocks       []byte             `json:"body_blocks"`
	TranscriptBlocks []byte             `json:"transcript_blocks"`
	Metadata         []byte             `json:"metadata"`
	RightsStatus     RightsStatus       `json:"rights_status"`
	Attribution      string             `json:"attribution"`
	Status           ContentStatus      `json:"status"`
	Revision         int32              `json:"revision"`
	SourceUpdatedAt  pgtype.Timestamptz `json:"source_updated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ReleasedAt       pgtype.Timestamptz `json:"released_at"`
	CanonicalUrl     string             `json:"canonical_url"`
	Rank             float32            `json:"rank"`
}

func (q *Queries) SearchPublishedContents(ctx context.Context, arg SearchPublishedContentsParams) ([]SearchPublishedContentsRow, error) {
	rows, err := q.db.Query(ctx, searchPublishedContents, arg.SearchQuery, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPublishedContentsRow{}
	for rows.Next() {
		var i SearchPublishedContentsRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceItemID,
			&i.Slug,
			&i.Type,
			&i.Title,
			&i.Summary,
			&i.Level,
			&i.PublishedAt,
			&i.DurationSeconds,
			&i.BodyBlocks,
			&i.TranscriptBlocks,
			&i.Metadata,
			&i.RightsStatus,
			&i.Attribution,
			&i.Status,
			&i.Revision,
			&i.SourceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
			&i.CanonicalUrl,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSeries = `-- name: UpsertSeries :one
INSERT INTO series (slug, title) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET title = EXCLUDED.title, updated_at = now()
RETURNING id, slug, title, description, level, source_item_id, status, created_at, updated_at
`

type UpsertSeriesParams struct {
	Slug  string `json:"slug"`
	Title string `json:"title"`
}

func (q *Queries) UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error) {
	row := q.db.QueryRow(ctx, upsertSeries, arg.Slug, arg.Title)
	var i Series
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.SourceItemID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
