// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePublishEvent(ctx context.Context, arg CreatePublishEventParams) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSourceSnapshot(ctx context.Context, arg CreateSourceSnapshotParams) (SourceSnapshot, error)
	CreateUserEvent(ctx context.Context, arg CreateUserEventParams) (int64, error)
	DeleteBookmark(ctx context.Context, arg DeleteBookmarkParams) error
	DeleteSession(ctx context.Context, tokenHash []byte) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetDeliverableAsset(ctx context.Context, id uuid.UUID) (Asset, error)
	GetPublishedContent(ctx context.Context, id uuid.UUID) (GetPublishedContentRow, error)
	GetSeries(ctx context.Context, id uuid.UUID) (Series, error)
	GetSourceItem(ctx context.Context, id uuid.UUID) (SourceItem, error)
	GetUserBySessionHash(ctx context.Context, tokenHash []byte) (User, error)
	LinkContentAsset(ctx context.Context, arg LinkContentAssetParams) error
	LinkContentCategoryBySlug(ctx context.Context, arg LinkContentCategoryBySlugParams) error
	LinkContentSeries(ctx context.Context, arg LinkContentSeriesParams) error
	ListBookmarks(ctx context.Context, userID uuid.UUID) ([]ListBookmarksRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListCategoryContents(ctx context.Context, arg ListCategoryContentsParams) ([]ListCategoryContentsRow, error)
	ListContentAssets(ctx context.Context, contentID uuid.UUID) ([]ListContentAssetsRow, error)
	ListContentsByStatus(ctx context.Context, arg ListContentsByStatusParams) ([]Content, error)
	ListProgress(ctx context.Context, userID uuid.UUID) ([]LearningProgress, error)
	ListPublishEventsAfter(ctx context.Context, arg ListPublishEventsAfterParams) ([]PublishEvent, error)
	ListPublishedContents(ctx context.Context, arg ListPublishedContentsParams) ([]ListPublishedContentsRow, error)
	ListSeries(ctx context.Context, limit int32) ([]Series, error)
	ListSeriesContents(ctx context.Context, seriesID uuid.UUID) ([]ListSeriesContentsRow, error)
	ListSourceItemsDueForFetch(ctx context.Context, limit int32) ([]SourceItem, error)
	ListUserEventsAfter(ctx context.Context, arg ListUserEventsAfterParams) ([]UserEvent, error)
	MarkSnapshotParsed(ctx context.Context, arg MarkSnapshotParsedParams) error
	RecordAppleIdentityTokenUse(ctx context.Context, arg RecordAppleIdentityTokenUseParams) error
	SearchPublishedContents(ctx context.Context, arg SearchPublishedContentsParams) ([]SearchPublishedContentsRow, error)
	SetContentStatus(ctx context.Context, arg SetContentStatusParams) (Content, error)
	SetSourceFetchState(ctx context.Context, arg SetSourceFetchStateParams) error
	UpsertAppleUser(ctx context.Context, appleSubject string) (User, error)
	UpsertAsset(ctx context.Context, arg UpsertAssetParams) (Asset, error)
	UpsertBookmark(ctx context.Context, arg UpsertBookmarkParams) error
	UpsertContent(ctx context.Context, arg UpsertContentParams) (Content, error)
	UpsertProgress(ctx context.Context, arg UpsertProgressParams) (LearningProgress, error)
	UpsertSeries(ctx context.Context, arg UpsertSeriesParams) (Series, error)
	UpsertSourceItem(ctx context.Context, arg UpsertSourceItemParams) (SourceItem, error)
}

var _ Querier = (*Queries)(nil)
