// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: source_items.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSourceSnapshot = `-- name: CreateSourceSnapshot :one
INSERT INTO source_snapshots (
    source_item_id, http_status, etag, last_modified, content_hash,
    object_key, parser_version, parse_state, error_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (source_item_id, content_hash) DO UPDATE
SET fetched_at = now(), http_status = EXCLUDED.http_status,
    etag = EXCLUDED.etag, last_modified = EXCLUDED.last_modified
RETURNING id, source_item_id, fetched_at, http_status, etag, last_modified, content_hash, object_key, parser_version, parse_state, error_code
`

type CreateSourceSnapshotParams struct {
	SourceItemID  uuid.UUID   `json:"source_item_id"`
	HttpStatus    int32       `json:"http_status"`
	Etag          pgtype.Text `json:"etag"`
	LastModified  pgtype.Text `json:"last_modified"`
	ContentHash   string      `json:"content_hash"`
	ObjectKey     string      `json:"object_key"`
	ParserVersion pgtype.Text `json:"parser_version"`
	ParseState    string      `json:"parse_state"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

func (q *Queries) CreateSourceSnapshot(ctx context.Context, arg CreateSourceSnapshotParams) (SourceSnapshot, error) {
	row := q.db.QueryRow(ctx, createSourceSnapshot,
		arg.SourceItemID,
		arg.HttpStatus,
		arg.Etag,
		arg.LastModified,
		arg.ContentHash,
		arg.ObjectKey,
		arg.ParserVersion,
		arg.ParseState,
		arg.ErrorCode,
	)
	var i SourceSnapshot
	err := row.Scan(
		&i.ID,
		&i.SourceItemID,
		&i.FetchedAt,
		&i.HttpStatus,
		&i.Etag,
		&i.LastModified,
		&i.ContentHash,
		&i.ObjectKey,
		&i.ParserVersion,
		&i.ParseState,
		&i.ErrorCode,
	)
	return i, err
}

const getSourceItem = `-- name: GetSourceItem :one
SELECT id, source, canonical_url, external_id, page_type, first_seen_at, last_seen_at, fetch_state, next_fetch_at FROM source_items WHERE id = $1
`

func (q *Queries) GetSourceItem(ctx context.Context, id uuid.UUID) (SourceItem, error) {
	row := q.db.QueryRow(ctx, getSourceItem, id)
	var i SourceItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.CanonicalUrl,
		&i.ExternalID,
		&i.PageType,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FetchState,
		&i.NextFetchAt,
	)
	return i, err
}

const listSourceItemsDueForFetch = `-- name: ListSourceItemsDueForFetch :many
SELECT id, source, canonical_url, external_id, page_type, first_seen_at, last_seen_at, fetch_state, next_fetch_at
FROM source_items
WHERE fetch_state IN ('discovered', 'scheduled', 'failed')
  AND (next_fetch_at IS NULL OR next_fetch_at <= now())
ORDER BY next_fetch_at NULLS FIRST, first_seen_at
LIMIT $1
`

func (q *Queries) ListSourceItemsDueForFetch(ctx context.Context, limit int32) ([]SourceItem, error) {
	rows, err := q.db.Query(ctx, listSourceItemsDueForFetch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SourceItem{}
	for rows.Next() {
		var i SourceItem
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.CanonicalUrl,
			&i.ExternalID,
			&i.PageType,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.FetchState,
			&i.NextFetchAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSnapshotParsed = `-- name: MarkSnapshotParsed :exec
UPDATE source_snapshots
SET parser_version = $2, parse_state = $3, error_code = $4
WHERE id = $1
`

type MarkSnapshotParsedParams struct {
	ID            uuid.UUID   `json:"id"`
	ParserVersion pgtype.Text `json:"parser_version"`
	ParseState    string      `json:"parse_state"`
	ErrorCode     pgtype.Text `json:"error_code"`
}

func (q *Queries) MarkSnapshotParsed(ctx context.Context, arg MarkSnapshotParsedParams) error {
	_, err := q.db.Exec(ctx, markSnapshotParsed,
		arg.ID,
		arg.ParserVersion,
		arg.ParseState,
		arg.ErrorCode,
	)
	return err
}

const setSourceFetchState = `-- name: SetSourceFetchState :exec
UPDATE source_items
SET fetch_state = $2,
    next_fetch_at = $3
WHERE id = $1
`

type SetSourceFetchStateParams struct {
	ID          uuid.UUID          `json:"id"`
	FetchState  SourceFetchState   `json:"fetch_state"`
	NextFetchAt pgtype.Timestamptz `json:"next_fetch_at"`
}

func (q *Queries) SetSourceFetchState(ctx context.Context, arg SetSourceFetchStateParams) error {
	_, err := q.db.Exec(ctx, setSourceFetchState, arg.ID, arg.FetchState, arg.NextFetchAt)
	return err
}

const upsertSourceItem = `-- name: UpsertSourceItem :one
INSERT INTO source_items (source, canonical_url, external_id, page_type, last_seen_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (source, canonical_url) DO UPDATE
SET external_id = COALESCE(EXCLUDED.external_id, source_items.external_id),
    page_type = CASE
        WHEN source_items.page_type LIKE 'article:%' AND EXCLUDED.page_type = 'article' THEN source_items.page_type
        ELSE COALESCE(EXCLUDED.page_type, source_items.page_type)
    END,
    last_seen_at = now()
RETURNING id, source, canonical_url, external_id, page_type, first_seen_at, last_seen_at, fetch_state, next_fetch_at
`

type UpsertSourceItemParams struct {
	Source       string      `json:"source"`
	CanonicalUrl string      `json:"canonical_url"`
	ExternalID   pgtype.Text `json:"external_id"`
	PageType     pgtype.Text `json:"page_type"`
}

func (q *Queries) UpsertSourceItem(ctx context.Context, arg UpsertSourceItemParams) (SourceItem, error) {
	row := q.db.QueryRow(ctx, upsertSourceItem,
		arg.Source,
		arg.CanonicalUrl,
		arg.ExternalID,
		arg.PageType,
	)
	var i SourceItem
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.CanonicalUrl,
		&i.ExternalID,
		&i.PageType,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.FetchState,
		&i.NextFetchAt,
	)
	return i, err
}
